### ISSUE TITLE
Sentry error for /rss/updates/2/

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1503]
http://sentry.support.akvo-ops.org/rsr/live/group/213/

**Comment by kardan** [comment]
url: http://rsr.akvo.org/rss/updates/2/

Stacktrace (most recent call last):

  File "django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/contrib/syndication/views.py", line 44, in __call__
    feedgen = self.get_feed(obj, request)
  File "django/contrib/syndication/views.py", line 193, in get_feed
    pubdate = make_aware(pubdate, tz)
  File "django/utils/timezone.py", line 358, in make_aware
    return timezone.localize(value, is_dst=None)
  File "pytz/tzinfo.py", line 349, in localize
    raise AmbiguousTimeError(dt)

**Comment by KasperBrandt** [comment]
I figured out which update was giving issues and changed the time, that fixed it (although it is still very slow).

However, the admin does give an internal server error for project 2. When looking at the error, it seems like it has something to do with django_nested_inlines. The only place we use that is in the results, so maybe we should remove the results of that project.

**Comment by KasperBrandt** [comment]
Should be fixed by the date change in project 2 (and the admin issue will be tackled by the admin replacement).

**Comment by KasperBrandt** [comment]
## Test plan
GIVEN /rss/updates/2/
WHEN visiting the RSS feed
THEN no error should be returned

This turned out to be a data issue on Live, so am not sure if we can test this on UAT.

**Comment by rumca** [comment]
still seeing the same `AmbiguousTimeError at /rss/updates/2/` on UAT, will double check against Live when we have done the release
