### ISSUE TITLE
Various Minor Issues 

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-rsr#1790]
@KasperBrandt @gabemart let me know if opening multiple issues is preferable, but figured since these were all pretty minor we could address them in one issue.

* ~~When you visit the MyIATI page there's some sort of react error~~ (fixed in #1815):

![screen shot 2015-09-01 at 13 45 58](https://cloud.githubusercontent.com/assets/3003031/9604575/6332f0fa-50b0-11e5-9380-97bb5669709c.png)

* ~~When you change the project status (active, cancelled etc) on the project editor the following error is thrown~~:

![screen shot 2015-09-01 at 13 44 32](https://cloud.githubusercontent.com/assets/3003031/9604588/788c5536-50b0-11e5-907f-e48b81b7ee76.png)

* ~~The header for every page except the MyProjects page contains the "Add Update" button - not sure if this is intentional or if we should add it for consistency's sake~~ (@KasperBrandt edit; intentional, since that button will then lead you to the MyProjects page, that'll only confuse users):

![screen shot 2015-09-01 at 13 45 20](https://cloud.githubusercontent.com/assets/3003031/9604625/ad300134-50b0-11e5-8031-b8a3968c7886.png)

* I'm not sure if it's desirable, but it might be nice to have the ability to unpublish a project through the project editor as well?

* On the date picker it might be nicer looking if we leave off days that aren't part of the selected month:

![screen shot 2015-09-01 at 13 39 34](https://cloud.githubusercontent.com/assets/3003031/9604534/2d53e124-50b0-11e5-8f15-27e1d0e91ea8.png)

Or else have some sort of coloration for dates that are in the same month, here's the FLOW one:

![screen shot 2015-09-01 at 13 42 43](https://cloud.githubusercontent.com/assets/3003031/9604557/4b981894-50b0-11e5-8f06-3ffd41365fb2.png)

* Lastly - for projects where no info is submitted (e.g. a user clicks add project but doesn't fill any of the fields before leaving) - perhaps we could have some sort of scheduled task that deletes projects which were created x days ago but have no info? I'm not sure if we'll end up with a lot of the below otherwise:

![screen shot 2015-09-01 at 13 46 38](https://cloud.githubusercontent.com/assets/3003031/9604750/3af6847a-50b1-11e5-8cc0-1418e23bfcd5.png)

**Comment by rumca** [comment]
toggleDonateButton issue fixed in #1788

**Comment by rumca** [comment]
Another minor issue, when a user clicks "View project page" on the project editor, the following error is thrown:

![screen shot 2015-09-02 at 13 50 35](https://cloud.githubusercontent.com/assets/3003031/9631962/37aae902-517c-11e5-9176-ad89a3c8eb1e.png)

**Comment by gabemart** [comment]
@rumca is the "View project page" issue still current? I just had a go of reproducing and was not able to

**Comment by KasperBrandt** [comment]
@rumca @gabemart If not, then I consider the issue fixed :)..

- The datepicker library doesn't allow for easy customisation, so we'll leave it as is (too much work otherwise).
- Unpublishing a project is something we don't want to encourage. It's possible in the backend, but it shouldn't be stimulated in the front-end. Although some users might want the functionality eventually..
- I agree on the 'empty projects'. Have to think how we'll handle that and will make a separate issue for that.
